cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #1b3533
selection_background  #b0ccc9
url_color             #4edad3

color0   #131313
color1   #fa8849
color2   #4eda58
color3   #fff14a
color4   #2fcfc7
color5   #00645f
color6   #4edad3
color7   #d3e4e4
color8   #808d8d
color9   #ffaf84
color10  #8cff95
color11  #fff68c
color12  #6cefe9
color13  #8cfff9
color14  #b5fffb
color15  #f6fffe
